[package]
name = "abugslife"
version = "0.1.0"
authors = ["trans"]

[dependencies]
rand = "0.3.0"
rustc-serialize = "0.3"
piston = "^0.27.0"
piston2d-graphics = "^0.19.0"
piston2d-opengl_graphics = "^0.37.0"
pistoncore-glutin_window = "^0.33.0"

